Repository ecatch-kyst/web, pull requests merged in 2019-03, with the labels that each got.

#63 Hot fix/delete translation
  CHANGELOG.md
  src/components/Profile/index.js
Labels: bug

#69 Feature/persistence firebase
  CHANGELOG.md
  src/lib/firebase.js
Labels: feature

#71 Feature/messages
  CHANGELOG.md
  package.json
  src/App.js
  src/components/Forms/Form.jsx
  src/components/Forms/FormInput.jsx
  src/components/Forms/components/Dropdown.jsx
  src/components/Forms/components/DropdownMap.jsx
  src/components/Forms/components/GeoPointField.jsx
  src/components/Forms/components/TextField.jsx
  src/components/Forms/components/TextInput.jsx
  src/components/Forms/components/dropdown.json
  src/components/Forms/forms.json
  src/components/Forms/tests/Form.test.js
  src/components/Forms/tests/FormInput.test.js
  src/components/Forms/tests/index.test.js
  src/components/Messages.jsx
  src/components/Messages/__tests__/index.test.js
  src/components/Messages/components/EditMessage.jsx
  src/components/Messages/components/Message.jsx
  src/components/Messages/components/Status.jsx
  src/components/Messages/components/TableHead.jsx
  src/components/Messages/components/tests/EditMessage.test.js
  src/components/Messages/index.js
  src/components/index.js
  src/components/shared/Page.jsx
  src/db/Store.js
  src/db/actions/__tests__/user.test.js
  src/db/actions/index.js
  src/db/actions/location.js
  src/db/actions/messages.js
  src/db/actions/user.js
  src/db/initialValues.json
  src/lib/i18next.js
  src/lib/router.js
  src/locales/en/common.json
  src/locales/en/dropdown.json
  src/locales/en/forms.json
  src/locales/en/messages.json
  src/locales/no/common.json
  src/locales/no/dropdown.json
  src/locales/no/forms.json
  src/locales/no/messages.json
  src/utils/firebase.js
  yarn.lock
Labels: feature

#73 🔖release/1.0.0-beta3
  CHANGELOG.md
  package.json
  src/App.js
  src/components/Forms/Form.jsx
  src/components/Forms/FormInput.jsx
  src/components/Forms/components/Dropdown.jsx
  src/components/Forms/components/DropdownMap.jsx
  src/components/Forms/components/GeoPointField.jsx
  src/components/Forms/components/TextField.jsx
  src/components/Forms/components/TextInput.jsx
  src/components/Forms/components/dropdown.json
  src/components/Forms/forms.json
  src/components/Forms/tests/Form.test.js
  src/components/Forms/tests/FormInput.test.js
  src/components/Forms/tests/index.test.js
  src/components/Messages.jsx
  src/components/Messages/__tests__/index.test.js
  src/components/Messages/components/EditMessage.jsx
  src/components/Messages/components/Message.jsx
  src/components/Messages/components/Status.jsx
  src/components/Messages/components/TableHead.jsx
  src/components/Messages/components/tests/EditMessage.test.js
  src/components/Messages/index.js
  src/components/Profile/index.js
  src/components/index.js
  src/components/shared/Page.jsx
  src/components/shared/__tests__/Page.test.js
  src/db/Store.js
  src/db/actions/__tests__/user.test.js
  src/db/actions/index.js
  src/db/actions/location.js
  src/db/actions/messages.js
  src/db/actions/user.js
  src/db/initialValues.json
  src/lib/firebase.js
  src/lib/i18next.js
  src/lib/router.js
  src/locales/en/common.json
  src/locales/en/dropdown.json
  src/locales/en/forms.json
  src/locales/en/messages.json
  src/locales/no/common.json
  src/locales/no/dropdown.json
  src/locales/no/forms.json
  src/locales/no/messages.json
  src/utils/firebase.js
  yarn.lock
Labels: feature

#81 Update enzyme-adapter-react-16 to the latest version 🚀
  package.json
  src/components/Landing/__tests__/__snapshots__/index.test.js.snap
  src/components/NotFound/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: greenkeeper

#60 new logo/app name
  .env
  CHANGELOG.md
  README.md
  public/192x192.png
  public/512x512.png
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon-114x114.png
  public/apple-touch-icon-120x120.png
  public/apple-touch-icon-144x144.png
  public/apple-touch-icon-152x152.png
  public/apple-touch-icon-180x180.png
  public/apple-touch-icon-57x57.png
  public/apple-touch-icon-60x60.png
  public/apple-touch-icon-72x72.png
  public/apple-touch-icon-76x76.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/eCatch_pilot_h.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/html_code.html
  public/index.html
  public/manifest.json
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  src/assets/eCatch_pilot_h.png
  src/components/Landing/__tests__/__snapshots__/index.test.js.snap
  src/components/Landing/index.js
Labels: good first issue, ui

#70 Feature/add fishing spot
  CHANGELOG.md
  src/components/Forms/FormInput.jsx
  src/components/Forms/components/AddFishingSpot.js
  src/components/Forms/components/Dropdown.jsx
  src/components/Forms/components/DropdownMap.jsx
  src/components/Forms/components/GeoPointInput.jsx
  src/components/Forms/components/TextInput.jsx
  src/components/Forms/components/__tests__/AddFishingSpot.test.js
  src/components/Forms/forms.json
  src/components/shared/Dialog.jsx
  src/db/Store.js
  src/db/actions/customLists.js
  src/db/actions/dialog.js
  src/db/actions/index.js
  src/db/actions/messages.js
  src/locales/en/common.json
  src/locales/en/forms.json
  src/locales/no/common.json
  src/locales/no/forms.json
Labels: feature

#94 ♻️ clean up in locales
  CHANGELOG.md
  src/App.js
  src/components/Forms/Form.jsx
  src/components/Forms/components/AddFishingSpot.js
  src/components/Forms/components/Dropdown.jsx
  src/components/Forms/components/DropdownMap.jsx
  src/components/Forms/tests/Form.test.js
  src/components/HomePage.jsx
  src/components/Landing/index.js
  src/components/Profile/index.js
  src/components/Profile/tests/index.test.js
  src/components/Register.jsx
  src/components/Trips/Trip/DCAOverview.jsx
  src/components/Trips/Trip/FishChip.jsx
  src/components/Trips/Trip/TripRow.jsx
  src/components/Trips/Trip/index.js
  src/components/index.js
  src/components/shared/Dialog.jsx
  src/components/shared/Notification.jsx
  src/components/tests/Dashboard.test.js
  src/components/tests/HomePage.test.js
  src/db/initialValues.json
  src/lib/i18next.js
  src/lib/router.js
  src/locales/birds.json
  src/locales/en/boats.json
  src/locales/en/common.json
  src/locales/en/dialogs.json
  src/locales/en/dropdowns.json
  src/locales/en/fishing_tools.json
  src/locales/en/forms.json
  src/locales/en/homepage.json
  src/locales/en/messages.json
  src/locales/en/notifications.json
  src/locales/en/pages.json
  src/locales/en/problems.json
  src/locales/en/profile.json
  src/locales/en/register.json
  src/locales/en/species.json
  src/locales/no/boats.json
  src/locales/no/common.json
  src/locales/no/dialogs.json
  src/locales/no/dropdowns.json
  src/locales/no/fishing_tools.json
  src/locales/no/forms.json
  src/locales/no/homepage.json
  src/locales/no/messages.json
  src/locales/no/notifications.json
  src/locales/no/pages.json
  src/locales/no/problems.json
  src/locales/no/profile.json
  src/locales/no/register.json
  src/locales/no/species.json
Labels: good first issue, help wanted

#98 Greenkeeper/monorepo.material ui 20190330022438
  package.json
  yarn.lock
Labels: greenkeeper
