Repository ecatch-kyst/web, pull requests merged in 2019-02, with the labels that each got.

#36 Hotfix/login form
  CHANGELOG.md
  src/components/Landing/index.js
Labels: bug

#37 Hotfix/no navigation on register
  CHANGELOG.md
  src/App.js
Labels: bug

#43 feature/in-app notification
  CHANGELOG.md
  src/App.js
  src/components/Profile/LanguageChooser.jsx
  src/components/Profile/__tests__/LanguageChooser.test.js
  src/components/index.js
  src/components/shared/DestructButton.jsx
  src/components/shared/Notification.jsx
  src/components/shared/__tests__/Notification.test.js
  src/components/shared/index.js
  src/db/Store.js
  src/db/actions/__tests__/darkMode.test.js
  src/db/actions/__tests__/notification.test.js
  src/db/actions/__tests__/users.test.js
  src/db/actions/darkMode.js
  src/db/actions/notification.js
  src/db/actions/users.js
  src/db/initialValues.json
  src/hooks/index.js
  src/hooks/useNotification.js
  src/lib/material-ui.js
  src/locales/en/common.json
  src/locales/no/common.json
Labels: feature

#44 🔧 update Lighthouse config
  .travis.yml
  bin/lighthouse.sh
  package.json
Labels: help wanted, reminder

#45 Feature/add to home screen
  CHANGELOG.md
  public/manifest.json
  src/a2hs.js
Labels: feature

#47 feature/messages
  CHANGELOG.md
  package.json
  src/App.js
  src/__tests__/App.test.js
  src/components/Boats.jsx
  src/components/Centered.jsx
  src/components/Dashboard.jsx
  src/components/Departure.jsx
  src/components/Forms/Form.jsx
  src/components/Forms/FormInput.jsx
  src/components/Forms/components/Dropdown.jsx
  src/components/Forms/components/DropdownMap.jsx
  src/components/Forms/components/TextField.jsx
  src/components/Forms/components/dropdown.json
  src/components/Forms/forms.json
  src/components/Forms/index.js
  src/components/Landing/__tests__/index.test.js
  src/components/Landing/index.js
  src/components/Messages.jsx
  src/components/index.js
  src/components/shared/Dialog.jsx
  src/components/shared/InputDropdown.js
  src/components/shared/Notification.jsx
  src/components/shared/Page.jsx
  src/db/Store.js
  src/db/actions/__tests__/dialog.test.js
  src/db/actions/__tests__/users.test.js
  src/db/actions/dialog.js
  src/db/actions/messages.js
  src/db/actions/notification.js
  src/db/actions/users.js
  src/db/initialValues.json
  src/lib/firebase.js
  src/lib/i18next.js
  src/lib/router.js
  src/locales/en/common.json
  src/locales/en/dashboard.json
  src/locales/en/dropdown.json
  src/locales/en/forms.json
  src/locales/en/messages.json
  src/locales/en/problems.json
  src/locales/en/species.json
  src/locales/latin/messages.json
  src/locales/message_types.json
  src/locales/no/common.json
  src/locales/no/dashboard.json
  src/locales/no/dropdown.json
  src/locales/no/forms.json
  src/locales/no/messages.json
  src/locales/no/problems.json
  src/locales/no/species.json
  src/utils/firebase.js
  src/utils/index.js
  src/utils/validate.js
  yarn.lock
Labels: feature

#48 feature/ui
  CHANGELOG.md
  src/components/shared/Notification.jsx
  src/components/shared/__tests__/Notification.test.js
  yarn.lock
Labels: feature

#58 Feature/prevent redirect
  CHANGELOG.md
  src/components/shared/Page.jsx
  src/components/shared/__tests__/Page.test.js
  src/db/actions/users.js
  src/db/initialValues.json
Labels: bug, feature
